name: lisiecka_aplikacje_mobilne
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.2.0


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5
  path_provider: ^2.0.11
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_database: ^11.3.0


  cupertino_icons: ^1.0.8
  very_good_analysis: ^7.0.0
  firebase_auth: ^5.4.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  generate: true
  assets:
    - assets/images/